version: "3.9"

services:
  backend:
    build: ./backend
    container_name: buyer-portal-backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend/data:/app/data
    environment:
      - PORT=4000
      - JWT_SECRET
    restart: unless-stopped
  

  frontend:
    build: ./frontend
    container_name: buyer-portal-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped